### ISSUE TITLE
Future Roadmap: Simplify deployment of the web package

### ISSUE THREAD

**Issue by adriankast** [eclipse-thingweb/playground#164]
Currently the web package requires a local installation (running `npm install` inside the package) and uses several bundled dependencies. There are different reasons for this, which are only partwise solveable, but should be at least improveable:
- [ ] The monaco editor overwrites the `require` function, thus it is not possible or at least quite difficult to browserify the whole `web` package.
- [ ] It could be better to browserify the depending packages inside the web package (and store all results in a `dist` folder in the web package), this would move, e.g., unpublished packages to `devDependencies` thus avoiding errors in the CD pipeline because the local installation is failing.
- [x] Some packages provide more than just their functionality, e.g., the `core` also ships examples, which are loaded during runtime, if one is needed. This makes it necessary to know the path to these modules and currently is another reason for the local installation being necessary. Still this could be *easily* solved by detecting where the depending modules are (under `node_modules` since `web` was installed as single package, in neighbor folders since the whole monorepo was bootstrapped, ...)

**Comment by egekorkan** [comment]
Not relevant anymore with the new package and using pure npm installation
